name: SimCore CI

on:
  workflow_dispatch:

  push:
    branches: [main, master]

  pull_request:

jobs:

  quality:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show clang-format version
        run: clang-format --version

      - name: Format Check
        run: python build.py --check-format

  docker:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t simcore .

      - name: Run Tests in Docker
        run: docker run --rm simcore